version: '3.8'

services:
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.1 6379
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.2 6379
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - keydb-data:/data
      - ./keydb.conf:/etc/keydb/keydb.conf
    ports:
      - 6379:6379
    restart: unless-stopped

  arangodb_db:
    image: arangodb:latest
    container_name: arango
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
    ports:
      - 8529:8529
    networks:
      - mangachan_net
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps


networks:
  mangachan_net:
    driver: bridge  

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
  keydb-data:
