// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: 01_settings.sql

package pgdb

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT setting_id, first_voucher FROM settings WHERE setting_id = $1
`

func (q *Queries) GetSetting(ctx context.Context, settingID int32) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, settingID)
	var i Setting
	err := row.Scan(&i.SettingID, &i.FirstVoucher)
	return i, err
}

const updateSettingVoucherNewbie = `-- name: UpdateSettingVoucherNewbie :one
UPDATE settings SET
first_voucher = $1
WHERE setting_id = $2 RETURNING setting_id, first_voucher
`

type UpdateSettingVoucherNewbieParams struct {
	FirstVoucher bool
	SettingID    int32
}

func (q *Queries) UpdateSettingVoucherNewbie(ctx context.Context, arg UpdateSettingVoucherNewbieParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettingVoucherNewbie, arg.FirstVoucher, arg.SettingID)
	var i Setting
	err := row.Scan(&i.SettingID, &i.FirstVoucher)
	return i, err
}
