// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 04_manga_detail.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMangaDetail = `-- name: CreateMangaDetail :exec
INSERT INTO manga_detail (
  detail_id,
	published,
	authors,
    artist,
	summary,
	updated_at,
	created_at
) VALUES (
  $1,$2,$3,$4,$5,$6,$7
)
`

type CreateMangaDetailParams struct {
	DetailID  int64
	Published pgtype.Text
	Authors   []string
	Artist    []string
	Summary   pgtype.Text
	UpdatedAt int64
	CreatedAt int64
}

func (q *Queries) CreateMangaDetail(ctx context.Context, arg CreateMangaDetailParams) error {
	_, err := q.db.Exec(ctx, createMangaDetail,
		arg.DetailID,
		arg.Published,
		arg.Authors,
		arg.Artist,
		arg.Summary,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}
