// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 05_manga_score.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMangaScore = `-- name: CreateMangaScore :exec
INSERT INTO manga_score (
  score_id,
	score,
	updated_at,
	created_at
) VALUES (
  $1,$2,$3,$4
)
`

type CreateMangaScoreParams struct {
	ScoreID   int64
	Score     pgtype.Numeric
	UpdatedAt int64
	CreatedAt int64
}

func (q *Queries) CreateMangaScore(ctx context.Context, arg CreateMangaScoreParams) error {
	_, err := q.db.Exec(ctx, createMangaScore,
		arg.ScoreID,
		arg.Score,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}
