// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 06_manga_cover.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMangaCover = `-- name: CreateMangaCover :one
INSERT INTO manga_cover (
  cover_id,
  cover_detail,
  thumbnail,
  extra,
  updated_at,
  created_at
) VALUES (
  $1,$2,$3,$4,$5,$6
) RETURNING cover_id
`

type CreateMangaCoverParams struct {
	CoverID     int64
	CoverDetail pgtype.Text
	Thumbnail   pgtype.Text
	Extra       []string
	UpdatedAt   int64
	CreatedAt   int64
}

func (q *Queries) CreateMangaCover(ctx context.Context, arg CreateMangaCoverParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMangaCover,
		arg.CoverID,
		arg.CoverDetail,
		arg.Thumbnail,
		arg.Extra,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var cover_id int64
	err := row.Scan(&cover_id)
	return cover_id, err
}
