// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 08_manga_genre.sql

package pgdb

import (
	"context"
)

const createMangaGenre = `-- name: CreateMangaGenre :exec
INSERT INTO manga_genre (
  mg_id,
  manga_id,
  genre_id,
  updated_at,
  created_at
) VALUES (
  $1,$2,$3,$4,$5
)
`

type CreateMangaGenreParams struct {
	MgID      int64
	MangaID   int64
	GenreID   int64
	UpdatedAt int64
	CreatedAt int64
}

func (q *Queries) CreateMangaGenre(ctx context.Context, arg CreateMangaGenreParams) error {
	_, err := q.db.Exec(ctx, createMangaGenre,
		arg.MgID,
		arg.MangaID,
		arg.GenreID,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	return err
}
