CREATE TABLE IF NOT EXISTS char (
	char_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	step INT NOT NULL,
	image TEXT DEFAULT '',
    voice TEXT DEFAULT '',
	en TEXT DEFAULT '',
	id TEXT DEFAULT '',
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);