CREATE TABLE IF NOT EXISTS lesson (
	lesson_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	title VARCHAR(100) NOT NULL,
    video_url TEXT DEFAULT '',
    number INT NOT NULL,
    is_free BOOLEAN NOT NULL DEFAULT FALSE,
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);